# coding=utf-8
"""
QuantNodes CLI - Command Line Interface.

This package is split for readability:
    _helpers.py          shared helpers + constants
    commands/init.py     ``quantnodes init``
    commands/run.py      ``quantnodes run`` (api/frontend start helpers)
    commands/chat.py     ``quantnodes chat``
    commands/evolve.py   ``quantnodes evolve`` (Week 5)
    commands/factor.py   ``quantnodes factor-*`` (Week 5~13)
    commands/version.py  ``quantnodes version`` / ``quantnodes help``

Public re-exports below keep ``from QuantNodes.cli import main`` and the
individual ``cmd_*`` symbols importable exactly as before the split.

Commands:
    init    - Initialize current directory
    run     - Start services
    version - Show version
    help    - Show this help message

Cache TTL alignment (H18): the .env template generated by
``write_env_file`` (in ``_helpers.py``) writes
``QUANTNODES__CACHE_TTL=604800``, kept in sync with
``IFindFetcher.DEFAULT_CACHE_TTL_S`` (7 * 86400).
"""

import sys
import argparse

from ._helpers import *  # noqa: F401,F403  (helpers + constants re-exported)
from ._helpers import (
    PROG_NAME,
    add_cli_overrides,
    add_lineage_depth_args,
    add_metric_arg,
    add_output_arg,
    add_pool_dir_arg,
    add_title_arg,
    add_top_arg,
)
from .commands.init import cmd_init
from .commands.run import (
    cmd_run,
    start_api_server as start_api_server,
    start_frontend_server as start_frontend_server,
)
from .commands.version import cmd_version, cmd_help
from .commands.chat import cmd_chat
from .commands.evolve import (
    cmd_evolve,
    _load_runner_from_config as _load_runner_from_config,
)
from .commands.factor import (
    cmd_factor_info,
    cmd_factor_best,
    cmd_factor_visual,
    cmd_factor_dashboard,
    cmd_factor_data_fetch,
    cmd_factor_rag_eval,
    cmd_factor_rag_show,
)


def _build_parser() -> argparse.ArgumentParser:
    """Build the top-level argparse parser (with all subcommands).

    Phase I1 (2026-06-20): repeated argument groups consolidated via
    builders in _helpers.py:
      add_pool_dir_arg (6 sites), add_top_arg (2), add_metric_arg (2),
      add_title_arg (2), add_output_arg (3), add_lineage_depth_args (2),
      add_cli_overrides (2).
    """
    parser = argparse.ArgumentParser(
        prog=PROG_NAME,
        description="QuantNodes CLI - 量化研究节点架构命令行工具",
        add_help=False
    )

    subparsers = parser.add_subparsers(dest="command", help="可用命令")

    init_parser = subparsers.add_parser("init", help="初始化当前目录")
    init_parser.add_argument("--force", action="store_true", help="强制重新初始化")

    run_parser = subparsers.add_parser("run", help="启动服务")
    run_parser.add_argument("--host", help="绑定主机")
    run_parser.add_argument("--port", type=int, help="前端端口")
    run_parser.add_argument("--api-port", type=int, dest="api_port", help="后端端口")
    run_parser.add_argument("--daemon", action="store_true", help="后台运行 (仅 Linux)")
    run_parser.add_argument("--api-only", action="store_true", dest="api_only", help="仅启动后端")
    run_parser.add_argument("--frontend-only", action="store_true", dest="frontend_only", help="仅启动前端")

    chat_parser = subparsers.add_parser("chat", help="启动 Agent 对话模式")
    chat_parser.add_argument("message", nargs="?", help="单次提问（不指定则进入交互模式）")
    chat_parser.add_argument("--workspace", default=".", help="工作目录")

    # Week 5: 演化实验子命令
    evolve_parser = subparsers.add_parser("evolve", help="多轮演化主入口")
    evolve_parser.add_argument("--config", required=True, help="YAML 配置文件路径")
    evolve_parser.add_argument("--directions", default="", help="逗号分隔的研究方向")
    evolve_parser.add_argument("--initial-json", default=None, help="初始 candidates JSON")
    evolve_parser.add_argument("--max-rounds", type=int, default=None, help="覆盖 config.max_rounds")
    evolve_parser.add_argument("--early-stop", type=int, default=None, help="覆盖 config.early_stop_patience")
    evolve_parser.add_argument("--workers", type=int, default=1, help="并行评估数 (默认 1=串行, >1=ThreadPool)")
    add_cli_overrides(evolve_parser)

    info_parser = subparsers.add_parser("factor-info", help="显示 TrajectoryPool 统计")
    add_pool_dir_arg(info_parser)

    best_parser = subparsers.add_parser("factor-best", help="显示 Top-N 最佳 entry")
    add_pool_dir_arg(best_parser)
    add_top_arg(best_parser)
    add_metric_arg(best_parser)

    visual_parser = subparsers.add_parser("factor-visual", help="生成可视化 HTML 报告 (Week 6)")
    add_pool_dir_arg(visual_parser)
    add_output_arg(visual_parser)
    add_metric_arg(visual_parser)
    add_title_arg(visual_parser)

    rag_parser = subparsers.add_parser("factor-rag-show", help="RAG 检索演示 (Week 7)")
    add_pool_dir_arg(rag_parser)
    rag_parser.add_argument("--query", required=True, help="查询文本")
    add_top_arg(rag_parser)
    rag_parser.add_argument("--compress", action="store_true", help="启用谱系压缩 (Week 9)")
    add_lineage_depth_args(rag_parser)
    rag_parser.add_argument("--max-tokens", type=int, default=200, help="压缩最大字符数 (默认 200)")

    rag_eval_parser = subparsers.add_parser("factor-rag-eval", help="批量评估 RAG 检索质量 (Week 10)")
    add_pool_dir_arg(rag_eval_parser)
    rag_eval_parser.add_argument("--queries", required=True, help="逗号分隔的 query 列表")
    add_top_arg(rag_eval_parser)
    add_lineage_depth_args(rag_eval_parser)
    add_output_arg(rag_eval_parser)

    fetch_parser = subparsers.add_parser("factor-data-fetch", help="从 iFinD 拉取数据 + 写 H5 (Week 12)")
    fetch_parser.add_argument("--output-dir", required=True, help="HDF5 输出目录")
    fetch_parser.add_argument("--date-beg", required=True, help="起始日期 (YYYYMMDD)")
    fetch_parser.add_argument("--date-end", default="", help="截止日期 (空=今天)")
    fetch_parser.add_argument("--universe", default="all", help="股票池 (默认 all, 与 iFinD API 兼容)")
    fetch_parser.add_argument("--factors", default="", help="逗号分隔的因子列表")
    add_cli_overrides(fetch_parser)

    dash_parser = subparsers.add_parser("factor-dashboard", help="生成 3 类指标 dashboard (Week 13/16)")
    add_pool_dir_arg(dash_parser)
    add_output_arg(dash_parser)
    add_title_arg(dash_parser)
    dash_parser.add_argument("--streaming", action="store_true", help="启用 streaming 模式 (自动刷新 10s)")
    dash_parser.add_argument("--refresh", type=int, default=10, help="streaming 刷新间隔秒数 (默认 10)")
    dash_parser.add_argument("--watch", action="store_true", help="后台模式: 每 10s 刷新 dashboard")

    subparsers.add_parser("version", help="显示版本")
    subparsers.add_parser("help", help="显示帮助")

    return parser


def main():
    """Main CLI entry point."""
    parser = _build_parser()
    args = parser.parse_args()

    if args.command == "init":
        return cmd_init(args)
    elif args.command == "run":
        return cmd_run(args)
    elif args.command == "chat":
        return cmd_chat(args)
    elif args.command == "evolve":
        return cmd_evolve(args)
    elif args.command == "factor-info":
        return cmd_factor_info(args)
    elif args.command == "factor-best":
        return cmd_factor_best(args)
    elif args.command == "factor-visual":
        return cmd_factor_visual(args)
    elif args.command == "factor-rag-show":
        return cmd_factor_rag_show(args)
    elif args.command == "factor-rag-eval":
        return cmd_factor_rag_eval(args)
    elif args.command == "factor-data-fetch":
        return cmd_factor_data_fetch(args)
    elif args.command == "factor-dashboard":
        return cmd_factor_dashboard(args)
    elif args.command == "version":
        return cmd_version(args)
    elif args.command == "help":
        return cmd_help(args)
    else:
        cmd_help(args)
        return 0


if __name__ == "__main__":
    sys.exit(main())
