# coding=utf-8
"""
QuantNodes CLI - Command Line Interface.

This package is split for readability:
    _helpers.py          shared helpers + constants
    commands/init.py     ``quantnodes init``
    commands/run.py      ``quantnodes run`` (api/frontend start helpers)
    commands/chat.py     ``quantnodes chat``
    commands/evolve.py   ``quantnodes evolve`` (Week 5)
    commands/factor.py   ``quantnodes factor-*`` (Week 5~13)
    commands/version.py  ``quantnodes version`` / ``quantnodes help``

Public re-exports below keep ``from QuantNodes.cli import main`` and the
individual ``cmd_*`` symbols importable exactly as before the split.

Commands:
    init    - Initialize current directory
    run     - Start services
    version - Show version
    help    - Show this help message

Cache TTL alignment (H18): the .env template generated by
``write_env_file`` (in ``_helpers.py``) writes
``QUANTNODES__CACHE_TTL=604800``, kept in sync with
``IFindFetcher.DEFAULT_CACHE_TTL_S`` (7 * 86400).
"""

import sys
import argparse

from ._helpers import *  # noqa: F401,F403  (helpers + constants re-exported)
# PROG_NAME 在本模块 _build_parser 中使用; 其余 add_* builders 现由各 Command
# 子类自行调用, 这里保留 re-export 仅为 backward compat (redundant-alias 显式标注).
from ._helpers import (
    PROG_NAME,
    add_cli_overrides as add_cli_overrides,
    add_lineage_depth_args as add_lineage_depth_args,
    add_metric_arg as add_metric_arg,
    add_output_arg as add_output_arg,
    add_pool_dir_arg as add_pool_dir_arg,
    add_title_arg as add_title_arg,
    add_top_arg as add_top_arg,
)
# cmd_* 函数 re-export: backward compat, ``from QuantNodes.cli import cmd_init`` 不变.
# Phase 3.1 起 main() 已改走 COMMAND_REGISTRY dispatch, 这些函数仅 cmd_help
# 在缺省分支直接调用, 其余靠各 Command.run() 间接调用.
from .commands.init import cmd_init as cmd_init
from .commands.run import (
    cmd_run as cmd_run,
    start_api_server as start_api_server,
    start_frontend_server as start_frontend_server,
)
from .commands.version import cmd_version as cmd_version, cmd_help
from .commands.chat import cmd_chat as cmd_chat
from .commands.evolve import (
    cmd_evolve as cmd_evolve,
    _load_runner_from_config as _load_runner_from_config,
)
from .commands.factor import (
    cmd_factor_info as cmd_factor_info,
    cmd_factor_best as cmd_factor_best,
    cmd_factor_visual as cmd_factor_visual,
    cmd_factor_dashboard as cmd_factor_dashboard,
    cmd_factor_data_fetch as cmd_factor_data_fetch,
    cmd_factor_rag_eval as cmd_factor_rag_eval,
    cmd_factor_rag_show as cmd_factor_rag_show,
)
from .commands import COMMAND_REGISTRY as COMMAND_REGISTRY


def _build_parser() -> argparse.ArgumentParser:
    """Build the top-level argparse parser (with all subcommands).

    Phase 3.1 (2026-06-22): 改为遍历 COMMAND_REGISTRY, 每个 Command 自己
    负责 add_arguments(subparsers). 替代原 90 行手写 parser 构造. 新增子
    命令只需写 Command 子类 + 在 commands/__init__.py 注册.

    Phase I1 (2026-06-20): repeated argument groups consolidated via
    builders in _helpers.py (add_pool_dir_arg 等), 现由各 Command 调用.
    """
    parser = argparse.ArgumentParser(
        prog=PROG_NAME,
        description="QuantNodes CLI - 量化研究节点架构命令行工具",
        add_help=False
    )
    subparsers = parser.add_subparsers(dest="command", help="可用命令")
    for cmd in COMMAND_REGISTRY.all():
        cmd.add_arguments(subparsers)
    return parser


def main():
    """Main CLI entry point.

    Phase 3.1 (2026-06-22): 改为 registry dispatch. 未知/缺省 command 回退
    到 help (与旧行为一致).
    """
    parser = _build_parser()
    args = parser.parse_args()

    cmd = COMMAND_REGISTRY.get(args.command)
    if cmd is None:
        return cmd_help(args)
    return cmd.run(args)


if __name__ == "__main__":
    sys.exit(main())
